[package]
name = "camloc-server"
version = "0.1.0"
edition = "2021"

[dependencies]
# TODO: camloc_common = { git = "https://github.com/Kris030/camloc_common" }
camloc_common = { path = "../common" }
tokio = { version = "1.27.0", features = [
	"time", "net", "rt", "sync", "macros", "io-util", "io-std", "rt-multi-thread", "fs"
] }
ctrlc = "3.2.5"
