[package]
name = "camloc_calibration_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
# TODO: camloc_common = { git = "https://github.com/Kris030/camloc_common" }
camloc_common = { path = "../common" }
clap = { version = "4.2.2", features = ["derive"] }
opencv = "0.80.0"
